### ISSUE TITLE
Testing coordination

### ISSUE THREAD

**Issue by kuegi** [kuegi/dusd-lock-bot#3]
@3DotsHub I deployed the latest version (imho should be final) to 0xeF0Bf6df74e15981FB182bE3914C14958aa409bb
also verified on mydefichain explorer

lockup of 1 day.

**Comment by 3DotsHub** [comment]
Hi @kuegi , i went through your changes. 
Is it on testnet?

Changed allAddresses as public, so solidity compiler will add a method to iterate through the array.
Added getAllAddresses, returning the array. 

Added few useful helpers.
Added one require in claimAllRewards, due it was possible to claim 0 rewards and write/change blockchain state. 

Changed from currentTVL to newRewardsClaimable:
```
event RewardsAdded(uint256 addedRewards, uint256 blocksSinceLastRewards, uint256 **newRewardsClaimable**);
event RewardsClaimed(address user, uint256 claimedRewards, uint256 **newRewardsClaimable**);
```
Due the RewardsAdded & RewardsClaimed methods do not change the TVL, they change "totalClaimableRewards" or "TVL of claimable rewards"

**Comment by kuegi** [comment]
> Hi @kuegi , i went through your changes. Is it on testnet?
> 
> Changed allAddresses as public, so solidity compiler will add a method to iterate through the array. Added getAllAddresses, returning the array.
> 
> Added few useful helpers. Added one require in claimAllRewards, due it was possible to claim 0 rewards and write/change blockchain state.
> 
> Changed from currentTVL to newRewardsClaimable:
> 
> ```
> event RewardsAdded(uint256 addedRewards, uint256 blocksSinceLastRewards, uint256 **newRewardsClaimable**);
> event RewardsClaimed(address user, uint256 claimedRewards, uint256 **newRewardsClaimable**);
> ```
> 
> Due the RewardsAdded & RewardsClaimed methods do not change the TVL, they change "totalClaimableRewards" or "TVL of claimable rewards"

Yes its on testnet, or at least my last version. I had the TVL in the RewardsAdded Event on purpose to make it easy to calc APR based on this.

I think the SC is ready now. Core team might adapt it anyway. lets keep it like that and wait for a UI so that the community can test.

**Comment by 3DotsHub** [comment]
> > Hi @kuegi , i went through your changes. Is it on testnet?
> > Changed allAddresses as public, so solidity compiler will add a method to iterate through the array. Added getAllAddresses, returning the array.
> > Added few useful helpers. Added one require in claimAllRewards, due it was possible to claim 0 rewards and write/change blockchain state.
> > Changed from currentTVL to newRewardsClaimable:
> > ```
> > event RewardsAdded(uint256 addedRewards, uint256 blocksSinceLastRewards, uint256 **newRewardsClaimable**);
> > event RewardsClaimed(address user, uint256 claimedRewards, uint256 **newRewardsClaimable**);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Due the RewardsAdded & RewardsClaimed methods do not change the TVL, they change "totalClaimableRewards" or "TVL of claimable rewards"
> 
> Yes its on testnet, or at least my last version. I had the TVL in the RewardsAdded Event on purpose to make it easy to calc APR based on this.
> 
> I think the SC is ready now. Core team might adapt it anyway. lets keep it like that and wait for a UI so that the community can test.

Totally understandable. Thanks for the type correction.
Great choice to add the currentTlv back again to the event. Now we have both values. 

Looks great to me. Thank you for collaborate together on this idea.

**Comment by 3DotsHub** [comment]
> > Hi @kuegi , i went through your changes. Is it on testnet?
> > Changed allAddresses as public, so solidity compiler will add a method to iterate through the array. Added getAllAddresses, returning the array.
> > Added few useful helpers. Added one require in claimAllRewards, due it was possible to claim 0 rewards and write/change blockchain state.
> > Changed from currentTVL to newRewardsClaimable:
> > ```
> > event RewardsAdded(uint256 addedRewards, uint256 blocksSinceLastRewards, uint256 **newRewardsClaimable**);
> > event RewardsClaimed(address user, uint256 claimedRewards, uint256 **newRewardsClaimable**);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Due the RewardsAdded & RewardsClaimed methods do not change the TVL, they change "totalClaimableRewards" or "TVL of claimable rewards"
> 
> Yes its on testnet, or at least my last version. I had the TVL in the RewardsAdded Event on purpose to make it easy to calc APR based on this.
> 
> I think the SC is ready now. Core team might adapt it anyway. lets keep it like that and wait for a UI so that the community can test.

Totally understandable. Thanks for the type correction.
Great choice to add the currentTlv back again to the event. Now we have both values.

Looks great to me. Thank you for collaborate together on this idea.
