### ISSUE TITLE
DEPOSIT Button is not enabled after approve

### ISSUE THREAD

**Issue by DeFiPages** [kuegi/dusd-lock-bot#4]
https://www.vault-maxi.live/defichain/testnet-dusd-locks:
after the approval transaction was executed, the deposit button was not enabled. I had to reload the page, enter the same amount, and then I could deposit.

**Comment by Krysh90** [comment]
Have observed the issue on my end once, too. Haven't found a fix yet. Will look through the code again.

If I am not able to find any fix, it will stay like this - as it is "only" a test UI and will not be "productively" used on mainnet
